# Use root/example as user/password credentials
version: '3.3'
services:
  db:
    image: neo4j:latest
    restart: always

    environment:
      - NEO4J_AUTH=neo4j/test
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - /neo4j/data:/Users/Aman/Documents/GitHub/Neo4j_Primer
      - C:\Users\Aman\Documents\GitHub\Neo4j_Primer:/AZM_TEST
